title: Ambrosio, JOse
description: > # this means to ignore newlines until "baseurl:"
  Git hub pages showcase website.
baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Ambrosio, Jose
tagline: Full Stack Developer
about-description: I'm a Web Developer with an interest in Android Development and Machine Learning.
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: jjambrosio1@gmail.com # Add your Email address
phone: 323 404 8222 # Add your Phone number
website: J-Ambrosio.com # Add your website, do not add http://
linkedin: jose-ambrosio-16a179152/ # Add your Linkedin handle
github: BtmnAmbrosio # Add your Github handle
twitter: '@btmn_Ambrosio' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
